# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2318d4f85fb5c5eac85768cf4a19f57b36eac6a5c1d7f6ce5d07c2446540aa43702eee2d47d572f752df12c8eff3fc6fe1ac066c56f1e1854e0b834ccecd1053

test:
  secret_key_base: c2c3e20c8c2c9aca73c1ba833ad20a9fb413ad4ae0905169f96ff888b6500c9614c0ca5ba2adc95a0e1f6a6f385db5f066f20f97552e8be801d35ee19075eeaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
